### ISSUE TITLE
Add filters for whitelist status & server version

### ISSUE THREAD

**Issue by sunguytogood** [xnite/MCSeeker#1]
Can you add options to search for servers with no whitelist and what version as well as exlude version?

**Comment by xnite** [comment]
I would be happy to do that. Though as far as I am aware a client-bot will be required for whitelist so that part may take some time and require extra steps at the end-user level to use that feature. The version filters I can do no problem and will push out fairly soon™.

**Comment by sunguytogood** [comment]
alright

**Comment by sunguytogood** [comment]
i think you can possibly join a server for a few seconds with mineflayer and then you get lots of information such as whitelist, version, block patterns etc

**Comment by xnite** [comment]
> i think you can possibly join a server for a few seconds with mineflayer and then you get lots of information such as whitelist, version, block patterns etc

yup! Already on it, nothing pushed quite yet but looks like it will work nicely. :)

**Comment by xnite** [comment]
Feature added in commit: a801231a84863f26ea8dda930924047eb8be6d0c
