### ISSUE TITLE
not getting any scans

### ISSUE THREAD

**Issue by Robthekilla** [xnite/MCSeeker#4]
whenever i scan it doesnt show any ip in the csv file

**Comment by Cabbasca** [comment]
are you running it with --out <filename>?

**Comment by xnite** [comment]
@Robthekilla please send the command, with options, that you are using. You can change ip range & file names if you'd like, but keep the rest the same to original command that you are having trouble with.

**Comment by Robthekilla** [comment]
It worked now but how do I use more anbigger ip range

**Comment by xnite** [comment]
It does up to a /10 before one of the underlying libraries tends to have an issue. But that's still enough to scan a pretty massive number of servers.

**Comment by xnite** [comment]
Since there are no new replies and this issue seems to be resolved I will close this now.
