### ISSUE TITLE
Reached heap limit Allocation failed on large scans

### ISSUE THREAD

**Issue by AndyIsHereBoi** [xnite/MCSeeker#5]
```
PS C:\Users\ANDY6\Downloads\MCSeeker-0.0.2>  node ./scanner.js --ip iprange/24 --port 0-65535 --show-desc --min-players 0 --max-players 100 --out report.csv
Scanning ports 0-65535 on iprange/24

<--- Last few GCs --->

[15700:00000296CAC2CE90]     6575 ms: Mark-Compact (reduce) 2046.6 (2080.9) -> 2046.5 (2081.1) MB, 325.6 / 0.0 ms  (+ 54.3 ms in 9 steps since start of marking, biggest step 7.5 ms, walltime since start of marking 418 ms) (average mu = 0.418, current mu =[15700:00000296CAC2CE90]     7186 ms: Mark-Compact (reduce) 2047.7 (2081.9) -> 2047.7 (2082.4) MB, 347.4 / 0.0 ms  (+ 35.9 ms in 8 steps since start of marking, biggest step 6.1 ms, walltime since start of marking 386 ms) (average mu = 0.395, current mu =

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF76EF384FF node_api_throw_syntax_error+176511
 2: 00007FF76EEBEC26 v8::base::CPU::num_virtual_address_bits+67734
 3: 00007FF76EEBFFE3 v8::base::CPU::num_virtual_address_bits+72787
 4: 00007FF76F9E9BC1 v8::Isolate::ReportExternalAllocationLimitReached+65
 5: 00007FF76F9D4816 v8::internal::V8::FatalProcessOutOfMemory+662
 6: 00007FF76F83AF30 v8::internal::EmbedderStackStateScope::ExplicitScopeForTesting+144
 7: 00007FF76F837F4D v8::internal::Heap::CollectGarbage+4749
 8: 00007FF76F84DB76 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath+2150
 9: 00007FF76F84E4AF v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath+95
10: 00007FF76F85D6D0 v8::internal::Factory::NewFillerObject+448
11: 00007FF76F51305F v8::internal::Runtime::SetObjectProperty+20719
12: 00007FF76FA93311 v8::internal::SetupIsolateDelegate::SetupHeap+606705
13: 00007FF6EFE12E1F```

**Comment by xnite** [comment]
The error says it all. The issue is that you're running out of memory to perform the operation with. Reduce port range to start and/or try a smaller IP range to scan.

**Comment by AndyIsHereBoi** [comment]
I have 16gb of ram and only like 5gb in use so unless it uses 11gb it shouldn't have issues
I was also watching the memory in task manager and it didn't report anything over 3gb on the process

**Comment by xnite** [comment]
Alright, probably an issue with what is allocated by nodejs for the script then. You could try increasing the limit by adding something like this after `node` and before the script name: `--max-old-space-size=8192`. This may allow up to 8GB by script. Could you see if that changes anything for you?

**Comment by AndyIsHereBoi** [comment]
A lot of these old issues I had are starting to get closed finally

**Comment by xnite** [comment]
@AndyIsHereBoi quite unresolved in this case unfortunately. Given the reason that it's happening it is sort of a won't fix or can't fix. However what I can do is offer you the peace of mind that if you use [this code](https://github.com/xnite/BBCrawler) then it's much more capable than the project which this issue is on. The BBCrawler project was actually written because of this one single issue. I will no recommend that for more complex operations and scans.

**Comment by AndyIsHereBoi** [comment]
> @AndyIsHereBoi quite unresolved in this case unfortunately. Given the reason that it's happening it is sort of a won't fix or can't fix. However what I can do is offer you the peace of mind that if you use [this code](https://github.com/xnite/BBCrawler) then it's much more capable than the project which this issue is on. The BBCrawler project was actually written because of this one single issue. I will now be recommending that one for more complex operations and scans.

I just meant that a lot of my first issues that I created on GitHub are starting to be closed after like years of inactivity
